server:
  port: 8080

# Rest API前缀地址
restPath: /api

# App信息
application:
  name: demo
  shortName: demo
  version: 1.1

logging.level:
  org.springframework: debug
  org.apache.shiro: debug
  org.hibernate.SQL: debug
  com.lcw.one: debug

# 文件服务文件存储地址
file.path: D:\Files

#=============================#
#===== Database Settings =====#
#=============================#
spring.datasource:
#  url: jdbc:mysql://127.0.0.1:3306/one?useUnicode=true&characterEncoding=utf-8
#  username: root
#  password: one
#  driver-class-name: com.mysql.jdbc.Driver

  url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=gpallas
  username: sa
  password: 123456
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  druid.initialSize: 3
  druid.maxActive: 3
  druid.minIdle: 2
  druid.maxWait: 60000
  druid.timeBetweenEvictionRunsMillis: 60000
  druid.minEvictableIdleTimeMillis: 300000
#  druid.validationQuery: SELECT 'x' FROM DUAL

#=============================#
#=====   Redis Settings  =====#
#=============================#
spring.redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  pool:
    max-active: 8
    max-wait: -1
    max-idle: 8
    min-idle: 0
  timeout: 0

